### ISSUE TITLE
convert does not always return Num

### ISSUE THREAD

**Issue by paulflang** [LCSB-BioCore/SBML.jl#100]
https://github.com/LCSB-BioCore/SBML.jl/blob/8957cfadd48a253d3373e34e02c94a119ac62aff/src/symbolics.jl#L100

I think we need to return `Num(conv(x))`

**Comment by exaexa** [comment]
whoops I pushed the fix to this to master by a mistake (SORRY!), but well it should be fixed now.

If not, please reopen with a test case.
