### ISSUE TITLE
Throw warning instead of error when not hOSU and compartment unsized

### ISSUE THREAD

**Issue by paulflang** [LCSB-BioCore/SBML.jl#101]
https://github.com/LCSB-BioCore/SBML.jl/blob/460dd7f6f05f0939c1d789d9c1b89daf6b22ea35/src/utils.jl#L120

There are several test-suite models failing due to this. Perhaps we should throw a warning instead of an error.

**Comment by exaexa** [comment]
What would be the thing to return in this case if the warning is triggered? I threw the error there because there aren't many other reasonable values left to return.

**Comment by paulflang** [comment]
Just return `x`. Case 00048 gives the correct simulation results if you do it like that.

**Comment by exaexa** [comment]
that, at the bare minimum, sounds extremely fishy. :D

What's the semantics of the result then?

**Comment by paulflang** [comment]
It does.

But since the sbml_test_suite includes this case and simulation results with it, it must be valid SBML. And since just returning `x` gives the correct simulation, it is very likely that this is the right interpretation.

I briefly looked at the specs how this case should be handled but unfortunately could not find anything. Maybe I've missed it. Otherwise, it is perhaps worth mentioning to the SBML developers @giordano ?

**Comment by exaexa** [comment]
so basically, missing volumes of compartments are in this case (or in all cases?) assumed to be 1.0 of whateverunitfitsthere, right?

**Comment by paulflang** [comment]
This is how I understand it.😭
