### ISSUE TITLE
writeSBML

### ISSUE THREAD

**Issue by exaexa** [LCSB-BioCore/SBML.jl#11]
There should be a straightforward equivalent of SBML import that just writes a minimal SBML with the given model.

**Comment by giordano** [comment]
I quickly looked at this today: libsbml has a convenient function [`writeSBML`](http://sbml.org/Software/libSBML/5.18.0/docs/formatted/c-api/class_s_b_m_l_writer__t.html#acd78335b9c61bb1f632219f6a28f23ae) to do that, but of course it takes as input... an [`SBMLDocument_t`](http://sbml.org/Software/libSBML/5.18.0/docs/formatted/c-api/class_s_b_m_l_document__t.html).

An alternative would be to use packages like [`EzXML.jl`](https://github.com/JuliaIO/EzXML.jl) or [`LightXML.jl`](https://github.com/JuliaIO/LightXML.jl) (I used `LightXML` in [`BinaryBuilder.jl`](https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/720e48f787db2790a6b4483685eaf72d61995e69/contrib/generate_instructions_list.jl)) to write the XML to a stream/file, but we also need to translate the `Model` back to something structured like the XML content of an SBML file.

**Comment by exaexa** [comment]
Manipulating XML directly is what we wanted to avoid (would be cool, but there's no assurance that we don't create a model that's off limits on some structural constraints).

Basically, the workflow would be to write a function that looks precisely as readSBML, but instead of stuff like `getNumReactions` and `getReaction` does `Reaction_create` and `Model_addReaction, then call SBML to write that to disk/string.

The API is usually close to the original functions; the usual way (everything is `listOf`) is the create→add→free as above. See eg. http://sbml.org/Software/libSBML/docs/c-api/class_reaction__t.html
