### ISSUE TITLE
`parseSBML` function to directly pass in an XML string 

### ISSUE THREAD

**Issue by anandijain** [LCSB-BioCore/SBML.jl#111]
it would work identically to readSBML, but the string of the model is in RAM, not saved to disk. It is annoying to have to save then read sometimes

**Comment by giordano** [comment]
Does SBML have this functionality?  I also wished it a few times, but I don't know if the upstream library has anything like that.

**Comment by giordano** [comment]
[`readSBMLFromString`](http://sbml.org/Software/libSBML/5.18.0/docs/formatted/c-api/class_s_b_m_l_reader__t.html#a74c8e0978b287df6dcedd45303f950d9)

**Comment by exaexa** [comment]
> it would work identically to readSBML, but the string of the model is in RAM, not saved to disk. It is annoying to have to save then read sometimes

why would you build XML in ram?

otherwise :+1: -- this looks pretty much straightforward
