### ISSUE TITLE
Adding `substoich` and `prodstoich` fields to `Reaction`

### ISSUE THREAD

**Issue by paulflang** [LCSB-BioCore/SBML.jl#119]
## Target functionality

Consider for instance reaction1 in [case 00054](https://github.com/sbmlteam/sbml-test-suite/blob/master/cases/semantic/00054/00054-sbml-l3v2.xml):
S1 + S2 -> 2*S2

When we create the Reaction.stoichiometry Dict, we get `Dict("S1"=>-1," S2"=>1)` .

This makes it impossible to identify further downstream whether the reaction kinetic is mass action. Therefore, I suggest to create two different fields: `substoich` and `prodstoich` in `Reaction`.

## Desired output

I would like to be able to do
```julia
ml = readSBML("case00054.xml")
@test isequal(ml.reactions["reaction1"].substoich, Dict("S1"=>1, "S2"=>1))
@test isequal(ml.reactions["reaction1"].prodstoich, Dict("S2"=>2))
```

## Suggestions for implementation

To make this change non-breaking, the `stoichiometry` field could return the sth like Reaction.prodstoich minus Reaction.substoich.

**Comment by exaexa** [comment]
I just found that some models contain `listOfModifiers`, would that be the correct way to refer to this?

**Comment by paulflang** [comment]
I see no need to include `listOfModifiers` in SBML.jl. AFAIK the only reason for their existence is to check if a `kineticLaw` is valid SBML. Per SBML specs a kineticLaw is invalid if it contains species that are not in `listOfReactants`, `listOfProducts` or `listOfModifiers`.

**Comment by exaexa** [comment]
http://sbml.org/Software/libSBML/docs/c-api/class_modifier_species_reference__t.html seems like precisely the case, "species is needed but isn't explicitly created or destroyed".

Anyway seems like this separation goes in next
