### ISSUE TITLE
Rename helper functions like `getS` to nicer names

### ISSUE THREAD

**Issue by exaexa** [LCSB-BioCore/SBML.jl#121]
random suggestions from the top of my head:

- `getS` → `stoichiometry_matrix`
- `getUB/LB` → `flux_bounds` (returns both, I can't see how anyone would want just lower or upper bounds)
- `getOC` → `flux_objective`

cc @giordano

**Comment by exaexa** [comment]
(originates in #120 )

**Comment by giordano** [comment]
> getUB/LB → flux_bounds (returns both, I can't see how anyone would want just lower or upper bounds)

While we're here, should `lb` and `ub` be `Number`s (product of value and units)?

**Comment by exaexa** [comment]
> While we're here, should `lb` and `ub` be `Number`s (product of value and units)?

Good question. For this "simplified" output it would be good to have them as Numbers, with some easy facitily to squash them down to a common unit.
