### ISSUE TITLE
expandInitialAssignments converter fails on case 01234

### ISSUE THREAD

**Issue by paulflang** [LCSB-BioCore/SBML.jl#125]
## Minimal code example to reproduce the problem
```julia
using SBMLToolkit
using Symbolics

case = "01234"
url = "https://raw.githubusercontent.com/sbmlteam/sbml-test-suite/master/cases/semantic/$case/$case-sbml-l3v2.xml"
tmpfile = download(url)
try
    SBMLToolkit.checksupport(tmpfile)
    ml1 = readSBML(tmpfile)  # works
    ml2 = readSBML(tmpfile, doc -> begin
            SBMLToolkit.SBML.libsbml_convert("expandInitialAssignments")(doc)
        end)  # fails
finally
    rm(tmpfile)
end
```

## Expected behavior

`ml1` and `ml2` should be the same, because the initialAssignment contains no mathML and according to the [test case descriptions](https://github.com/sbmlteam/sbml-test-suite/blob/master/cases/semantic/01234/01234-model.m) should therefore be ignored. It could be that I am doing sth wrong or the problem is rooted in SBML.jl or in the libSBML C API. At least setting `report_severities = []` does not help (if it has to do with the libSBML API we should report this there @giordano )

## Actual behavior
```
ERROR: LoadError: InexactError: Bool(-3)
Stacktrace:
 [1] Bool
   @ .\float.jl:106 [inlined]
 [2] check_errors (repeats 2 times)
   @ C:\Users\wolf5212\.julia\packages\SBML\XMU1n\src\utils.jl:202 [inlined]
 [3] (::SBML.var"#3#4"{Vector{Pair{String, Dict{String, String}}}})(doc::Ptr{Nothing})
   @ SBML C:\Users\wolf5212\.julia\packages\SBML\XMU1n\src\converters.jl:48
 [4] (::var"#37#38")(doc::Ptr{Nothing})
   @ Main c:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Programmes\juliadev\dev\Sandbox\mwe_case00851.jl:12
 [5] readSBML(fn::String, sbml_conversion::var"#37#38"; report_severities::Vector{String})
   @ SBML C:\Users\wolf5212\.julia\packages\SBML\XMU1n\src\readsbml.jl:113
 [6] readSBML(fn::String, sbml_conversion::Function)
   @ SBML C:\Users\wolf5212\.julia\packages\SBML\XMU1n\src\readsbml.jl:105
 [7] top-level scope
   @ c:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Programmes\juliadev\dev\Sandbox\mwe_case00851.jl:9
in expression starting at c:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Programmes\juliadev\dev\Sandbox\mwe_case00851.jl:7
```

**Comment by exaexa** [comment]
the InexactError sounds a bit like the conversion fails and returns something different than {0,1}.

Maybe the `Bool(retval)` was too optimistic?

**Comment by giordano** [comment]
> Maybe the Bool(retval) was too optimistic?

Looks like it:

* http://sbml.org/Software/libSBML/5.18.0/docs/formatted/c-api/operation_return_values_8h.html#a87d90022619ee855654b2b8f4997886d
* https://github.com/sbmlteam/libsbml/blob/d4bc12abc4e72e451a0a0f2be4b0b6101ac94160/src/sbml/common/operationReturnValues.h#L59-L281

I'm going to open a pull request to fix this.
