### ISSUE TITLE
case 01296 fails

### ISSUE THREAD

**Issue by paulflang** [LCSB-BioCore/SBML.jl#139]
## Minimal code example to reproduce the problem

```julia
case = "01296"
url = "https://raw.githubusercontent.com/sbmlteam/sbml-test-suite/master/cases/semantic/$case/$case-sbml-l3v2.xml"
tmpfile = download(url)
try
    SBMLToolkit.checksupport(tmpfile)
    ml = readSBML(tmpfile, doc -> begin
            set_level_and_version(3, 2)(doc)
            convert_simplify_math(doc)
        end)
    println(ml.reactions["J1"].kinetic_math)
finally
    rm(tmpfile)
end
```

## Expected behavior

Insertion of the rate of change of `p1` in kinetic_math (see specs p25).

## Actual behavior

prints `SBML.MathApply("rateOf", SBML.Math[SBML.MathIdent("p1")])`

**Comment by paulflang** [comment]
A similar problem occurs in 01459

**Comment by exaexa** [comment]
What is the expected SBML math you'd get? (also, if this is really a problem, I don't think we can solve it in SBML.jl, rather open a bug in libsbml)

**Comment by paulflang** [comment]
`SBML.MathApply("*", SBML.Math[SBML.MathIdent("p1"), SBML.MathVal(0.01)])`, bacause the ODE that describes p1 is `p1' = 0.01*p1`. I do not see a reason why this could not be solved in SBML.jl.

But I think there is an argument to be made that this expansion of `reateOf` should be handled by libSBML.

**Comment by exaexa** [comment]
How would that extend to situations if there would be more reactions producing/consuming `p1`, depending with production rates on each other? (in short, this it would require SBML.jl to solve ODEs, which it won't).

OTOH the 'rateOf' should be handled somehow. Is there some reasonable julia representation of that? would `'` aka `prime` work?

**Comment by exaexa** [comment]
(how's "derivation" marked in symbolics?)

**Comment by paulflang** [comment]
AFK, but I don't think we need derivatives for this. We just need the sum of all the kineticLaws the species participates in. Times stoichiometry of course.

**Comment by exaexa** [comment]
OK that's reinterpretation of the contents. Isn't there a function for that in libsbml already?

**Comment by exaexa** [comment]
(side question, what if the kinetic law will depend on the output of the reaction you're writing the kinetic law for?)

**Comment by paulflang** [comment]
Thanks for suggesting the cleaner way of reproducing the bug. To your question

> But 0.01 comes from J0, not J1, or am I missing something?

We have importantly have to insert the `rateOf`, or in other words time derivative of `p1` here, because of the `csymbol` element in
```
<apply>
    <csymbol encoding="text" definitionURL="http://www.sbml.org/sbml/symbols/rateOf"> rateOf </csymbol>
    <ci> p1 </ci>
```
I don't think that this makes any biological sense here, but it is just an artificial test case. According to the specs on p25-26

> The rateOf for the amount of a Species having attribute boundaryCondition=\false" and
appearing in one or more reactions can be calculated from the stoichiometries and KineticLaw Math
of every Reaction in which the species appears, plus appropriate conversionFactor values (see
Section 4.11.7 on p. 77).

Here, the the only reaction that changes `p1` is `J0`. Thus dp1/dt = 0.01 * p1.

**Comment by giordano** [comment]
Do we have any concept of "time" in `SBML.jl`?  How do we tell that `p1` varies over time?

**Comment by paulflang** [comment]
SBML.jl `Species` have the `boundary_condition` attribute. If that is `false` it means that the `Species` is time varying. How it is varying is described in the `kineticMath` attribute of the SBML.jl `Reaction` struct. In addition to that, there is the `MathTime` time struct, which is needed for ODEs of the form `x' = f(x, t)` (and not needed in ODEs of the form `x' = f(x)`).

**Comment by giordano** [comment]
Yes, I just found `MathTime`, thanks :slightly_smiling_face:

**Comment by paulflang** [comment]
Yeah, but bear in mind that this is only needed for about 1 percent of all ODE models, when SBMLToolkit constructs ODEs with Symbolics/ModelingToolkit expressions.

**Comment by exaexa** [comment]
heyho, can you please check if this works with current `master` ?

**Comment by paulflang** [comment]
I get `UndefVarError: sbmlrateOf not defined` when calling `SBMLToolkit.ReactionSystem(ml)`. I am using
```
  [e5567a89] SBML v0.8.1 `../SBML.jl#master`
  [86080e66] SBMLToolkit v0.1.9
```
Perhaps in the line https://github.com/LCSB-BioCore/SBML.jl/blob/df45fe48640005d2e20fecd2e04c9c26d9b71c02/src/symbolics.jl#L54
we need brackets like so: `"rateOf" => :(sbmlrateOf)`?
If that is the case, I assume we will need brackets for many other mappings, too.

**Comment by giordano** [comment]
>  we need brackets like so: `"rateOf" => :(sbmlrateOf)`?

No:
```julia
julia> :(sbmlrateOf) === :sbmlrateOf
true
```

**Comment by exaexa** [comment]
ok whoops, `sbmlRateOf` vs `sbmlrateOf` :]

**Comment by exaexa** [comment]
anyway, Symbolics now correctly compute that:
```julia
julia> convert(Num,ml.reactions["J1"].kinetic_math)
0
```

that's I guess not the result we wanted right? :D

**Comment by exaexa** [comment]
Anyway #159 fixes this to:
```julia
julia> convert(Num,ml.reactions["J1"].kinetic_math)
Differential(t)(p1)
```
which is I guess right.

**Comment by paulflang** [comment]
I was expecting sth like `dx/dt`. But I think the problem is that `Symbolics.derivative(x, MathTime("t"))` actually directly returns the results of dx/dt, which is zero unless you account for the kineticLaw in reaction J2, which it cannot, cause it is not aware of that.

**Comment by exaexa** [comment]
yeah just fixed that, the Differential(t)(p1) should have that meaning.

**Comment by paulflang** [comment]
curious to see if MTK/Catalyst does the right substitution when it sees two derivatives in one equation (dx/dt = f(dy/dt)).

**Comment by exaexa** [comment]
well let's hope. The variables originaging from the same `"t"` should be considered identical.

**Comment by paulflang** [comment]
Before your last commit our `getunidirectionalcomponents()` complained that it "Cannot separate bidirectional kineticLaw `0` to forward and reverse part. Please make reaction irreversible or rearrange kineticLaw to the form `term1 - term2`."

Now I get "MethodError(TermInterface.operation, (p1,), 0x0000000000007513)"

**Comment by exaexa** [comment]
wtf level: 10. I tried the literal commit of last code.

What's the code you are running to get that error message?

**Comment by exaexa** [comment]
ah that comes from checksupport() right? the `0` camed from deriving `p1` by `t` using `Symbolics.derivative`; now you'll probably need to add support for Differential() somewhere.

**Comment by paulflang** [comment]
I just ran the SBMLBioModelsRepository#pl-testing3 branch.
I also tested `checksupport()`, which worked. But
```julia
using SBML, SBMLToolkit, Downloads
case = "01296"
url = "https://raw.githubusercontent.com/sbmlteam/sbml-test-suite/master/cases/semantic/$case/$case-sbml-l3v2.xml"
str = String(take!(Downloads.download(url, IOBuffer())))
ml = readSBMLFromString(str, doc -> begin
                            set_level_and_version(3, 2)(doc)
                            convert_simplify_math(doc)
                        end)
ml.reactions["J1"].kinetic_math
ReactionSystem(ml)
```
gives
`MethodError: no method matching operation(::SymbolicUtils.Sym{Real, Base.ImmutableDict{DataType, Any}})`, which is different from the error before, but don't ask me why.
