### ISSUE TITLE
SBML doesn't respect math <cn> rationals

### ISSUE THREAD

**Issue by anandijain** [LCSB-BioCore/SBML.jl#140]
```xml
<kineticLaw>
    <math xmlns="http://www.w3.org/1998/Math/MathML">
        <cn type="rational">1<sep />5000</cn>
    </math>
</kineticLaw>
```
to reproduce just add `<cn type="rational">1<sep />5000</cn>` to any kineticLaw

```julia
m = readSBML(...)
m.reactions["reaction1"].kinetic_math
```
I get a `SBML.MathVal{Float64}(0.0002)` instead of a rational. it looks like the issue is just https://github.com/LCSB-BioCore/SBML.jl/blob/master/src/math.jl#L60 

I tried adding a 
```julia 
    elseif ast_is(ast, :ASTNode_isRational)
        return MathVal(ccall(sbml(:ASTNode_getRational), Cint, (VPtr,), at))
```
While `isRational` exists, sadly: 

>Rational numbers are represented in an AST node using separate numerator and denominator values. These can be retrieved using the methods ASTNode::getNumerator() and ASTNode::getDenominator(). [source](http://sbml.org/Software/libSBML/5.18.0/docs/cpp-api/class_a_s_t_node.html)

So I'm not exactly sure how to fix it, why they don't just have a `getRational` is beyond me.

**Comment by exaexa** [comment]
what's our fav/recommended julia representation of rationals?

**Comment by exaexa** [comment]
i.e., is `1//5000` a good representation of the above?

(side note: ohmygod who invented putting <sep/> into XML?!!!)

**Comment by anandijain** [comment]
yeah the builtin rational is what im using. i mean most of the time it'll just get promoted anyways but for correctness it makes me feel better lol
