### ISSUE TITLE
Tag?

### ISSUE THREAD

**Issue by ChrisRackauckas** [LCSB-BioCore/SBML.jl#149]
The tag is still missing from https://github.com/LCSB-BioCore/SBML.jl/pull/148. The Julia standard practices (https://github.com/SciML/ColPrac) include continuous release processes as a standard that would be good to follow if this is to be considered a core dependency.

**Comment by exaexa** [comment]
just checking -- by "the tag is still missing" you mean "it's still not released" ?

I wrote you on slack on whether to release this or wait for something else, I guess we just release then. :]
