### ISSUE TITLE
Cannot load any model

### ISSUE THREAD

**Issue by stelmo** [LCSB-BioCore/SBML.jl#16]
Hi, thanks for writing this package, I think it is a really valuable contribution to Julia's ecosystem! However, I am having some difficulty loading any model except the `Ec_core_flux1.xml` model that is used in the testing script. I have tried `iMM904.xml`, `iJO1366.xml` and `e_coli_core.xml` all recently downloaded from BIGG, see below for my code:

```julia
using SBML

# modelpath = joinpath("models", "iMM904.xml") # doesn' work
# modelpath = joinpath("models", "iJO1366.xml") # doesn't work
modelpath = joinpath("models", "e_coli_core.xml") # doesn't work
# modelpath = joinpath("models", "Ec_core_flux1.xml") # works, the model is loaded and seems functional

model = readSBML(modelpath) 
```
The error thrown is:

```julia
ERROR: 
Stacktrace:
 [1] readSBML(::String) at C:\Users\St. Elmo\.julia\packages\SBML\1vqCD\src\readsbml.jl:14
 [2] top-level scope at REPL[3]:1ERROR: UndefRefError: access to undefined reference
Stacktrace:
 [1] getproperty at .\Base.jl:33 [inlined]
 [2] showerror(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::SystemError) at .\errorshow.jl:128
 [3] (::Base.var"#689#690"{SystemError})(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}) at .\errorshow.jl:90
 [4] with_output_color(::Function, ::Symbol, ::IOContext{Base.TTY}; bold::Bool) at .\util.jl:72
 [5] with_output_color(::Function, ::Symbol, ::IOContext{Base.TTY}) at .\util.jl:70
 [6] showerror(::IOContext{Base.TTY}, ::SystemError, ::Array{Base.StackTraces.StackFrame,1}; backtrace::Bool) at .\errorshow.jl:89
 [7] showerror at .\errorshow.jl:88 [inlined]
 [8] display_repl_error(::Base.TTY, ::SystemError, ::Array{Union{Ptr{Nothing}, Base.InterpreterIP},1}) at c:\Users\St. Elmo\.vscode\extensions\julialang.language-julia-1.1.27\scripts\packages\VSCodeServer\src\repl.jl:124
 [9] evalrepl(::Module, ::Expr, ::REPL.LineEditREPL, ::REPL.LineEdit.Prompt) at c:\Users\St. Elmo\.vscode\extensions\julialang.language-julia-1.1.27\scripts\packages\VSCodeServer\src\repl.jl:96
 [10] top-level scope at c:\Users\St. Elmo\.vscode\extensions\julialang.language-julia-1.1.27\scripts\packages\VSCodeServer\src\repl.jl:83
```
Do you know what is going wrong?

**Comment by exaexa** [comment]
Hello! thanks for the feedback, this certainly needs to get tested on as many datasets as possible.

I'll have a look at the models (please share URLs just to make sure we're working on the same data). Anyway, I've tested the package on `e_coli_core.xml` before and it worked; at least given you're referring to the same model I tried, with just under 100x100 S matrix.

**Comment by stelmo** [comment]
Thanks for getting back to me! Yes, I think we are referring to the same model. Below are the links:

1) `e_coli_core.xml`: http://bigg.ucsd.edu/static/models/e_coli_core.xml
2) `iMM904.xml`: http://bigg.ucsd.edu/static/models/iMM904.xml
3) `iJO1366.xml`: http://bigg.ucsd.edu/static/models/iJO1366.xml

I was wondering if it may have something to do with the SBML level. The model's I couldn't load are all level 3+ and the `Ec_core_flux1.xml` is level 2. However, if you could load the `e_coli_core.xml` then it might not be that.

**Comment by exaexa** [comment]
Seems like the SBML call `readSBML` really fails on those (reporting more than 1 error). Sadly, libSBML error reporting is a bit archaic, I'll try to see what's actually failing. Stay tuned. :]

**Comment by exaexa** [comment]
After improving the error reporting, I got this:
```
julia> readSBML("e_coli_core.xml")
┌ Warning: SBML reported error: Every SBML Level 3 package is identified uniquely by an XML namespace URI and defines the attribute named 'required'. LibSBML has detected what appears to be an SBML Level 3 package with required=false but this instance of libSBML-5 cannot find the code necessary to parse this information.
│  Package 'fbc' is not a required package. The information relating to 'fbc' will be saved but cannot be interpreted.
└ @ SBML ~/work/SBML.jl/src/readsbml.jl:16
ERROR: AssertionError: Opening SBML document has reported errors
```
Can you parse the error? If I got it correctly, it's missing some "extra" package `fbc` that is not enabled by default in SBML?

**Comment by exaexa** [comment]
(anyway, would there some list of "recommended" extra packages that I should enable right away when fixing this? :D)

**Comment by stelmo** [comment]
Ah, yes I ran into something similar when I tried to use ccall on libsbml. I am digging up the old code now, I will get back to you soon (hopefully I got it working back then and can help you). As for recommended packages, I am not sure. Definitely fbc for constraint based models but I was under the impression that it is bundled with libsbml (however, I am not super familiar with the internals... I typically just used cobrapy and didn't care what went on under the hood)

**Comment by exaexa** [comment]
The problem is, it seems, that almost none of the extra packages are enabled by default, and I'm doing a default build because I somehow assumed that "default" will be the most "error-proof". Let's see. :]

**Comment by stelmo** [comment]
So I just downloaded the latest libsbml (v5.19) and used ccall to load the models and everything seems to work. I was essentially using your code in `readsbml.jl` but pointing to my local libsbml.dll package instead of the one you supply/build as part of SBML.jl, e.g. 
```julia
ccall((:readSBML, "libsbml.dll"), Ptr{Cvoid},(Cstring,), "e_coli_core.xml")
```
works. So I think you are correct that the extra packages are not enable by your default build. Let me know if I can help with anything?

**Comment by exaexa** [comment]
Is there a list of packages enabled in the official build or is it just "all of them" ? :D

**Comment by exaexa** [comment]
(PS the julia library builder is here: https://github.com/JuliaPackaging/Yggdrasil/blob/master/S/SBML/build_tarballs.jl )

**Comment by stelmo** [comment]
I think these packages are installed by default: http://sbml.org/Software/libSBML/5.18.0/docs/cpp-api/usergroup0.html

**Comment by exaexa** [comment]
I patched the build to enable everything; so far it seems that all tests have passed (see https://github.com/JuliaPackaging/Yggdrasil/pull/2613 ). The loading should get fixed when Yggdrasil PR gets pulled (+ some time for publishing the new version). You may need to manually install the new `SBML_jll` version after that (should work with normal `]add`).

**Comment by exaexa** [comment]
AAAAAAAAND that was fast, PR is now merged.

@stelmo could you please give it a try in around 1-2 hours from now (so that the updates have some time to bubble through) and confirm that it's fixed?

**Comment by stelmo** [comment]
Awesome, thank you so much for fixing this so quickly!! I really appreciate it! Yes, I will update the packages and test it. For interests sake, where did you read to add `-DENABLE_FBC=ON` to the build?

**Comment by exaexa** [comment]
I'm usually doing a blind build (just `cmake ..`) and then look at all the variables in CMakeCache and modify them as needed; ENABLE_FBC was just sitting there.

Also, if you type `cmake -D` and press tab, shell autocomplete may give some hints, at least if you have it enabled.

There might be a more sophisticated method but I'm not really good with cmake.

**Comment by stelmo** [comment]
Ah okay, good to know. Thanks :)

**Comment by stelmo** [comment]
Okay, I think we are making progress because the old error is gone, but it has been replaced by:
```julia
ERROR: ArgumentError: cannot convert NULL to string
Stacktrace:
 [1] unsafe_string at .\strings\string.jl:56 [inlined]
 [2] unsafe_string at .\c.jl:193 [inlined]
 [3] extractModel(::Ptr{Nothing}) at C:\Users\St. Elmo\.julia\packages\SBML\1vqCD\src\readsbml.jl:83
 [4] readSBML(::String) at C:\Users\St. Elmo\.julia\packages\SBML\1vqCD\src\readsbml.jl:23
 [5] top-level scope at REPL[3]:1
```
when importing a model, e.g. `iMM904.xml`. Strangely `Ec_core_flux1.xml` still works; note, as mentioned, you have to manually update or add `SBML_jll` to move on to this error from the previous one 😁. I thought this new error might just be an outdated function call in `extractModel`, so I forked the repo and dived into the code. Alas, I ran into problems. I tried decomposing `extractModel` into its parts but something is going horribly wrong. Below is a MWE. In short most `get...` functions causes Julia to crash.
```julia
using SBML
using SBML_jll, Libdl
const VPtr = Ptr{Cvoid}
sbml = (sym::Symbol) -> dlsym(SBML_jll.libsbml_handle, sym)

fn = "iJO1366.xml" # make sure your path to the model is set appropriately
doc = ccall(sbml(:readSBML), VPtr, (Cstring,), fn) # works
n_errs = ccall(sbml(:SBMLDocument_getNumErrors), Cuint, (VPtr,), doc) # works
mdl = ccall(sbml(:SBMLDocument_getModel), VPtr, (VPtr,), doc) # works
ccall(sbml(:SBMLDocument_free), Nothing, (VPtr,), doc) # works

ccall(sbml(:Model_getNumCompartments), Cuint, (VPtr,), mdl) # this works = 0x00000003
ccall(sbml(:Model_getCompartment), VPtr, (VPtr, Cuint), mdl, 1) # this crashes, similar with most of the get functions that return pointers
```

Similar issues arise for `Model_getCompartment`, etc. Interestingly, when I removed the SBML_jll dependency and just used the manually installed `libsbml.dll` in `ccall` everything works (minor code modifications required though*). It might be worth it to just require the user to install `libsbml` themselves and point Julia to it (the install steps are super easy).

*minor modifications e.g. `ccall((:Model_getCompartment, "libsbml.dll"), VPtr, (VPtr, Cuint), mdl, 1)` for the last line as an example.

**Comment by exaexa** [comment]
Ok I found this is integer underflow mistake (who would have said that we'll have C errors again! :] ). Fix impending.

**Comment by exaexa** [comment]
Can you try from this branch? https://github.com/LCSB-BioCore/SBML.jl/tree/mk-fix-nulls (`e_coli_core.xml` works properly for me now).

**Comment by stelmo** [comment]
It works 🥳  I tried all the models and everything loads correctly 😄 Thanks for helping out with this! Fiy, the issue with my decomposed code was that I was calling `SBMLDocument_free` before I did any manipulations, rookie mistake.

**Comment by exaexa** [comment]
Ah, happens :]
I'll merge that to the main code ASAP and push that to Julia packaging. Thanks for reporting!
