### ISSUE TITLE
Model attributes

### ISSUE THREAD

**Issue by anandijain** [LCSB-BioCore/SBML.jl#175]
Is there a way to get the rest of the attributes of the `<model metaid="_case00031" id="case00031" name="case00031" timeUnits="time">`. its not super important though, but its one of those things that could make the `show` nicer

**Comment by exaexa** [comment]
So the list is
- `metaid`
- `id`
- `name`
- time units are actually supported by #174 

any other stuff? A complete listing of gettable stuff is here but AFAIK we're pretty much done now :D https://sbml.org/software/libsbml/5.18.0/docs/formatted/c-api/class_model__t.html#a6295e49f9eb0bb4dd928b4a325ae46a8

**Comment by giordano** [comment]
If I'm reading https://github.com/sbmlteam/libsbml/blob/development/src/sbml/Model.cpp#L4896-L4906 correctly, in Level 3 the Model attributes are
* `name`
* `id`
* `substanceUnits`
* `timeUnits`
* `volumeUnits`
* `areaUnits`
* `lengthUnits`
* `extentUnits`
* `conversionFactor`
