### ISSUE TITLE
SBML model does not load with reaction or metabolite annotations

### ISSUE THREAD

**Issue by HettieC** [LCSB-BioCore/SBML.jl#208]
```
using COBREXA
download("http://bigg.ucsd.edu/static/models/e_coli_core.xml", "e_coli_core.xml")
model = load_model(StandardModel,"e_coli_core.xml");
model.reactions["R_ACONTb"].annotations

```
Expected result: list of the below reaction annotations, which are present in the JSON model. The SBML model passes the memote.io metabolite annotation test so presumably the SBML version does contain the same annotations as the JSON version of the model.
```   Reaction.annotations: 
bigg.reaction: ["ACONTb"]
metanetx.reaction: ["MNXR95387"]
rhea: 22145, ..., 22147
sbo: ["SBO:0000176"]
seed.reaction: ["rxn01388"]
kegg.reaction: ["R01900"]
ec-code: ["4.2.1.3"]
```

Actual behavior: an empty dictionary is produced when ```model.reactions["R_ACONTb"].annotations``` is called:

```Dict{String, Vector{String}}()Dict{String, Vector{String}}()```

Note: the same issue occurs with metabolites.

**Comment by exaexa** [comment]
So actually--

the "annotations" from JSON models seem to be more like SBOTerms and CVTerms in SBML. In fact, CobraPy saves these precisely as SBO and CV terms: https://github.com/opencobra/cobrapy/blob/devel/src/cobra/io/sbml.py#L1881

This therefore revives ye olde issue #27 :D

**Comment by exaexa** [comment]
@HettieC in #235 we're parsing out actual URIs of the linked identifiers (from identifiers.org), you will be able to rely on these when 1.3 is released (hopefully soon). One side issue that's left is that you'll need to interpret the URIs yourself to get the cobrapy-like form that you can see in JSONs, but that should be super easy.

Example output with #235:
```julia
julia> using SBML

julia> m = readSBML("work/COBREXA.jl/test/downloaded/e_coli_core.xml")
SBML.Model with 95 reactions, 72 species, and 5 parameters.

julia> m.reactions["R_ACONTb"].cv_terms[1]
SBML.CVTerm(
    :is,                 # <-- important part to check
    nothing,        # <-- there might be a different kind of qualifier here (likely also :is)
    [
        "http://identifiers.org/bigg.reaction/ACONTb",
        "http://identifiers.org/ec-code/4.2.1.3",
        "http://identifiers.org/kegg.reaction/R01900",
        "http://identifiers.org/metanetx.reaction/MNXR95387",
        "http://identifiers.org/rhea/22145",
        "http://identifiers.org/rhea/22144",
        "http://identifiers.org/rhea/22146",
        "http://identifiers.org/rhea/22147",
        "http://identifiers.org/seed.reaction/rxn01388",
    ],
    SBML.CVTerm[],
)
```

Code to convert stuff to JSON-like annotations:
```julia
julia> [
           =>(match(r"https?:\/\/identifiers\.org\/([^/]+)\/([^/]+)", uri).captures...) for
           c = m.reactions["R_ACONTb"].cv_terms if c.biological_qualifier == :is for
           uri in c.resource_uris
       ]

9-element Vector{Pair{SubString{String}, SubString{String}}}:
     "bigg.reaction" => "ACONTb"
           "ec-code" => "4.2.1.3"
     "kegg.reaction" => "R01900"
 "metanetx.reaction" => "MNXR95387"
              "rhea" => "22145"
              "rhea" => "22144"
              "rhea" => "22146"
              "rhea" => "22147"
     "seed.reaction" => "rxn01388"
```

(there's likely straightforward way there to make it a dictionary-of-sets as with json, but I'm not sure now)

**Comment by HettieC** [comment]
Cool, thank you
