### ISSUE TITLE
Add `exponentiale` to `default_constants`

### ISSUE THREAD

**Issue by paulflang** [LCSB-BioCore/SBML.jl#213]
https://github.com/LCSB-BioCore/SBML.jl/blob/b89c973c3da2f4cfd115a128fb2d4d33ea10c84e/src/interpret.jl#L97

Case 892 needs this. Page 21 in the specs describes this.

**Comment by paulflang** [comment]
Yes, this is also how I get it.

**Comment by exaexa** [comment]
Closed by #215
