### ISSUE TITLE
writing/exporting SBML

### ISSUE THREAD

**Issue by anandijain** [LCSB-BioCore/SBML.jl#239]
I realized we don't have an open issue on this. I think it's a natural question to have even if theres no plans to implement it

**Comment by giordano** [comment]
You mean beside [`writeSBML`](https://lcsb-biocore.github.io/SBML.jl/stable/functions/#SBML.writeSBML-Tuple{SBML.Model,%20String})?  Or what do you mean exactly?

**Comment by anandijain** [comment]
oh shoot, i thought we got rid of that 🤦
