### ISSUE TITLE
Support StoichiometryMath

### ISSUE THREAD

**Issue by sebapersson** [LCSB-BioCore/SBML.jl#258]
## Target functionality

In SBML level 2 StoichiometryMath is allowed (should be noted it is not supported for SBML level 3). The code I would like to work is;

```julia
using SBML
using Downloads
path = Downloads.download("https://raw.githubusercontent.com/sbmlteam/sbml-test-suite/release/cases/semantic/00068/00068-sbml-l2v5.xml", joinpath(@__DIR__, "model.xml"))
model = readSBML(path)
r1 = model.reactions["reaction1"]
r1.products[1].stoichiometry
```

## Desired output

Here as this reaction has a StoichiometryMath element the return would be (in the form of MathApply):

```julia
2*p1
```

## Optional: Suggestions for implementation

The relevant documentation can be found here https://sbml.org/software/libsbml/5.18.0/docs/formatted/c-api/class_stoichiometry_math__t.html. I am not entirely sure how to add it, but I figure that the best approach would be to allow for `SBML.SpeciesReference.stoichiometry` to be a more advanced math expression in case `stoichiometryMath` is present in the model.

This is maybe most relevant feature as stoichiometryMath only is supported for level2. However, as our PEtab.jl SBML importer currently supports majority of features for ODE models (except primarily events with delay, events with priority, and  species conversion factor see #257), for completness it would be awesome to have this features!

**Comment by paulflang** [comment]
(Not sure if relevant, but in the early days I think we decided to only focus on supporting SBML L3V2 and use [set_level_and_versions](https://github.com/LCSB-BioCore/SBML.jl/blob/62ab21bf99d465e9fb6befec2fc4f6abc4d1ed97/src/converters.jl#L9-L28) for everything else. Would that not work here?)

**Comment by exaexa** [comment]
@paulflang yeah good point. Kinda wondering what would the conversion do in this case though, is there any place where the math would get offloaded?

**Comment by sebapersson** [comment]
A check from my part, would [set_level_and_versions](https://github.com/LCSB-BioCore/SBML.jl/blob/62ab21bf99d465e9fb6befec2fc4f6abc4d1ed97/src/converters.jl#L9-L28) be able to transform level 2 SBML model with StoichiometryMath to a level 3 model (with the StoichiometryMath correctly handled?)

**Comment by paulflang** [comment]
Maybe in an assignmentRule?

**Comment by exaexa** [comment]
looks from here https://github.com/sbmlteam/libsbml/blob/1e15d62146d96686f9a321a305b292aa8195cc49/src/sbml/SBMLConvert.cpp#L1120-L1149 like it actually converts stuff to assignmentRules.

@sebapersson can you check if this would be OK for you? it should convert the rules as follows:
- there is going to be a new parameter identified by SpeciesReference field `id`
- the SpeciesReference is gonna be marked as not constant
- the math will be in an assignment rule identified by the `id` form S.R.

If there is any problem with the conversion, we could actually implement this quite easily -- there's support for math parsing already, and you can add it to the SpeciesReference parsing as a new field with a bit of copypaste, just as with the 2 fields in the other issue....

**Comment by sebapersson** [comment]
Thanks a lot, this works well for the case above!

I still have to go through the SBML test-suite to see that no problem pops up with the conversion, and if that happens I will reopen the issue.

**Comment by exaexa** [comment]
OK, thanks for the info! Please feel free to reopen with a testsuite ID in case you find any problems
