### ISSUE TITLE
support reading of the CV terms

### ISSUE THREAD

**Issue by exaexa** [LCSB-BioCore/SBML.jl#27]
SBML supports some parsing of (possibly recursive) CV terms; that would be cool to have implemented too.

Any ideas about what should be the Julia representation of CV terms are very welcome.

**Comment by exaexa** [comment]
These are isomorphic to JSON/cobrapy annotations. Must have™. :grimacing:

**Comment by exaexa** [comment]
libsbml supports a nice set of views over the annotation XML that should IMO be able to support the same set of functionality as users can very weirdly do now with the stringish XML; views described here: https://sbml.org/software/libsbml/5.18.0/docs/formatted/c-api/class_c_v_term__t.html

@skeating a quick question -- is the set of classes provided by libSBML for doing this (CVTerm, ModelCreator, ModelHistory, Date, ... maybe RDFAnnotationParser?) complete in regard of covering the MIRIAM specification for annotations?

**Comment by skeating** [comment]
yes libsbml annotations are miriam compliant

**Comment by exaexa** [comment]
perfect, thanks!
