### ISSUE TITLE
Converting SBML.Math types to Symbolics.jl

### ISSUE THREAD

**Issue by paulflang** [LCSB-BioCore/SBML.jl#47]
To proceed with #40 we need to have `SBML.Reactions.kinetic_math` in Symbolics.jl (no distinction between variables and parameters needed, as this will be handled downstream). Currently we use the `SBML/src/math.jl` parser which outputs `SBML.Math` types . Can we use the `MathML.jl`  parser instead? Alternatively, can sb write a `SBML.Math` to Symbolics.jl converter?

**Comment by paulflang** [comment]
Can sb remember why we used `SBML/src/math.jl` rather than `MathML.jl`?

**Comment by anandijain** [comment]
Yes when I looked at this sublanguage, it was not clear how to essentially avoid re-writing MathML.jl

**Comment by exaexa** [comment]
Hello! some quick explanations:

> Can sb remember why we used SBML/src/math.jl rather than MathML.jl?

> Yes when I looked at this sublanguage, it was not clear how to essentially avoid re-writing MathML.jl

There's one big "meh" in there, SBML is using MathML to encode the math for saving in XML, *BUT* internally the representation is a bit different. SBML.jl represents what the libsbml API provides, which is the different one.

I get a few questions about how Symbolics work for mechanical expression generation, I'll ask around and let you know.

**Comment by exaexa** [comment]
I've made a simple implementation here:
https://gist.github.com/exaexa/59d2e76a61f5207d369a3ed9c0dfe5b0
There's one ugly trick with unchecked `eval` but it should generally work. Later you may want to check the imported symbols against a dictionary of allowed ones, to prevent random call injections.

Given the weight of Symbolics library vs. (almost zero) weight of this piece of code, I guess this can be kept outside SBML.jl without any serious problems, would that be okay for you?

**Comment by paulflang** [comment]
> I guess this can be kept outside SBML.jl

From my perspective, eventually the whole conversion from SBML.jl to MTK.ReactionSystem, including the math conversion, can happen outside SBML.jl.

I just think that other developers might want to use SBML.jl as a dependency of their software in the future. And like me, they might benefit from math being represented in Symbolics, which would be a reason to keep it in SBML.jl.

**Comment by exaexa** [comment]
hm, good point.

@laurentheirendt is there any good way to include code that depends on another package without actually requiring that package?

(Or maybe we can just pack up symbolics too...)

**Comment by anandijain** [comment]
There is a package Requires.jl that sounds like what we want here

**Comment by exaexa** [comment]
Seems like this is getting solved already in #40, closing for tidyness.
