### ISSUE TITLE
Reversible Reaction handling through direct lowering to ODESystem

### ISSUE THREAD

**Issue by anandijain** [LCSB-BioCore/SBML.jl#51]
Frank pointed out that there is not an unambiguous way to lower these reversible ones to ReactionSystem, but it would be possible to lower directly to ODESystem. 

This wouldn't be part of #40 but good to have an issue tracking this, separate from ReactionSystem lowering stuff

**Comment by paulflang** [comment]
This is handled in SBMLToolkit: https://github.com/SciML/SBMLToolkit.jl/blob/2ef9c3c6d4c91555ec2c28b8dce5f322cfaaa98d/src/reactionsystem.jl#L153
