### ISSUE TITLE
Conversion of `piecewise` kineticLaws`

### ISSUE THREAD

**Issue by paulflang** [LCSB-BioCore/SBML.jl#52]
Some SBML documents specify piecewise kineticLaws multiplied with a constant (e.g. `c1`)
```Julia
SBML.MathApply("*", SBML.Math[
    SBML.MathIdent("c1"),
    SBML.MathApply("piecewise", SBML.Math[
        SBML.MathVal(1.0),
        SBML.MathApply("lt", SBML.Math[
            SBML.MathIdent("s2"), SBML.MathVal(0.1)]),
        SBML.MathVal(0.5)])])
```
I implemented `piecewise` in a9a19af:

```Julia
function parse_piecewise(val, cond, other)
    () -> cond ? val : other
end
```
Unfortunately there is no method to multiply its output with a constant. What works is:
```Julia
using SBML

@parameters c1
@variables s1 s2

pw = SBML.MathApply("piecewise", SBML.Math[
               SBML.MathVal(1.0),
               SBML.MathApply("lt", SBML.Math[
                   SBML.MathIdent("s2"), SBML.MathVal(0.1)]),
               SBML.MathVal(0.5)])
pw_sym = convert(Num, pw)
reac = ModelingToolkit.Reaction(pw_sym,[s1],[s2],[1],[1])
```
What fails is
```Julia
c1 * pw_sym
```
```
Closest candidates are:
  *(::Any, ::Any, ::Any, ::Any...) at operators.jl:560
  *(::ChainRulesCore.Tangent, ::Any) at C:\Users\wolf5212\.julia\packages\ChainRulesCore\qbmEe\src\differential_arithmetic.jl:191
  *(::ChainRulesCore.AbstractThunk, ::Any) at C:\Users\wolf5212\.julia\packages\ChainRulesCore\qbmEe\src\differential_arithmetic.jl:163
```
Any ideas how I can solve this?

**Comment by exaexa** [comment]
`parse_piecewise` seems to me more like evaluation than parsing. Can you supply a bit more context?

**Comment by exaexa** [comment]
Uh found it.
What about this:
```
     "piecewise" => (cond,t,f) -> cond?t:f,
```
(IMO your code has one extra empty lambda that won't get evaluated and can't be multiplied)

**Comment by exaexa** [comment]
OK nope, symbolics can't convert results of `>` to booleans automagically, try
```
@variables x y z
x > y ? z : z
```
I get:
```
julia> x > y ? z : z
ERROR: TypeError: non-boolean (Num) used in boolean context
```

Any idea how to actually convert it? (Symbolics docs is pretty sparse there)

**Comment by paulflang** [comment]
thanks for looking into that @exaexa . so the thing is that `x > y` needs to be evaluated at simulation time. x or y may be species that change in concentration.

**Comment by exaexa** [comment]
the late evaluation should be handled by symbolics, the only problem is that I have no idea how to write a working conditional in symbolics :D

**Comment by paulflang** [comment]
[MathML.jl uses IfElse](https://github.com/SciML/MathML.jl/blob/d9a1ef99d6fbd773b2fca0f4c0f877a2f84c8f6b/src/parse.jl#L98) and that works here, too.
```Julia
using IfElse

@variables x y z
z*IfElse.ifelse(x < y, z, z)  # z*IfElse.ifelse(x < y, z, z)
```
I implemented that in f23b0c1 but get a different error now for the SBML.Math expression at the very top of this GitHub issue (to be sorted tomorrow ):
```
MethodError: no method matching isless(::Tuple{Nothing, Nothing, Sym{Real, Nothing}}, ::Float64)
```

**Comment by exaexa** [comment]
o nice. Do you have a traceback for that error? Looks like < is getting applied to something it shouldn't be applied to.

**Comment by paulflang** [comment]
ah, solved it already. thanks!
