### ISSUE TITLE
Representation of independent `time` variable in SBML.Model

### ISSUE THREAD

**Issue by paulflang** [LCSB-BioCore/SBML.jl#54]
Currently test cases where the independent variable representing time occurs in the kineticLaw fail (see for instance [case 00852](https://github.com/sbmlteam/sbml-test-suite/blob/52d94baf97a005b6e1fdbdb6116f5c7b4a8a100c/cases/semantic/00852/00852-sbml-l3v2.xml#L69) and [AST_NAME_TIME](http://model.caltech.edu/software/libsbml/5.18.0/docs/formatted/c-api/class_a_s_t_node__t.html)). Is there a chance to parse time to Catalyst.DEFAULT_IV (see suggestion [here](https://github.com/paulflang/SBML.jl/blob/ea554218a17731cbdf1c2f189c04ac3bcc39e652/src/math.jl#L26). Or even better, create a SBML.jl native default_iv so that the Catalyst dependency can be removed from SBML.jl when we create an own repo for the MTK converter)?

**Comment by exaexa** [comment]
kinda trying to find how to parse this out. Is time a completely special case?

**Comment by exaexa** [comment]
(Copying the conv from julia slack here: )

So, can anyone explain what happens if I call getName on an SBML ASTNode that represents the AST_NAME_TIME? Referring to this here:
https://github.com/LCSB-BioCore/SBML.jl/issues/54
Peering at the source I'd say it should say something like time except that case doesn't seem to be handled in the source
( https://github.com/sbmlteam/libsbml/blob/development/src/sbml/math/ASTNode.cpp#L1175 )

notably, there's code like this one

      if (fd.getBody()->getType() == AST_NAME_TIME)
      {
        specialCase = true;
      }

which doesn't really reduce fishiness

**Comment by exaexa** [comment]
So actually, it looks like the thing is (somehow) represented just right as a variable name `time`; you may put the substitution for that into your evaluation scope and literally fill in whatever way you need.

Stuff loaded from the demo file looks like this:
```
julia> print(format_text(string(readSBML("00852-sbml-l3v2.xml"))))
SBML.Model(
    Dict("k3" => 1.0, "k1" => 0.7, "k2" => 0.5),
    Dict{String,Vector{SBML.UnitPart}}(
        "volume" => [SBML.UnitPart("litre", 1, 0, 1.0)],
        "time" => [SBML.UnitPart("second", 1, 0, 1.0)],
        "substance" => [SBML.UnitPart("mole", 1, 0, 1.0)],
    ),

#............

    Dict{String,SBML.Reaction}(
        "reaction1" => SBML.Reaction(
            Dict("S1" => -1.0, "S2" => 1.0),
            (-Inf, ""),
            (Inf, ""),
            0.0,
            nothing,
            SBML.MathApply(
                "*",
                SBML.Math[
                    SBML.MathApply(
                        "*",
                        SBML.Math[
                            SBML.MathApply(
                                "*",
                                SBML.Math[SBML.MathIdent("C"), SBML.MathIdent("k1")],
                            ),
                            SBML.MathIdent("S1"),
                        ],
                    ),
                    SBML.MathIdent("time"),          ← here we go
                ],
            ),
            nothing,
            nothing,
        ),

#.............
```
...which is likely the best way we can do now, except perhaps for adding special "MathTime" type for this particular case, which I guess is not really reasonable. Is there any reason for disambiguating it?

**Comment by paulflang** [comment]
I think we should aim for conversion from SBML to `SBML.Model` without information loss. Downstream handling would be simpler if we hat a `MathTime` type for that (or a `MathVal{time}` type). Atm case 00852 fails with `MethodError(*, (0.0, time), 0x0000000000007594)`. I guess I could do the disambiguation downstream, but I feel this is sth that belongs into SBML.jl. Otherwise all tools using it would have to find their own solution of how to do the disambiguation.

**Comment by exaexa** [comment]
Where does it fail? I'm loading that without any problems.

**Comment by paulflang** [comment]
loading works without problems. idk exactly where it fails. but `time` is neither a parameter nor a variable in SBML.Model and therefore also never created as MTK parameter/variable. So it must fail. Perhaps it is also of wrong type for multiplication. Like I said, perhaps it could be handled downstream, but if future tools want to SBML.jl, too they might run into the same issue. So I think the disambiguation belongs into SBML.jl.

**Comment by exaexa** [comment]
Oh I see, the value of `time` is not supplied anywhere from SBML (it can't) so the naive evaluator will inevitably fail. Yeah that checks, you need to fill that in as a variable, inevitably.

**Comment by paulflang** [comment]
So is there a way you can parse time into a special type that represents time/independent variable? Cause in SBML it kind of is. I can then easily convert that to `Catalyst.DEFAULT_IV`.

**Comment by exaexa** [comment]
I'm searching through SBML docs now, it looks like there's simply no function for telling whether the name is the time.
Can you just match the name `time` and add the DEFAULT_IV for that?

**Comment by paulflang** [comment]
Yeah, really annoying. They have `ASTNode_isInteger`, `ASTNode_isName` but no `ASTNode_isTime`, despite there is an AST node of type `AST_NAME_TIME`. Is there no libsmbl function that returns the type of the AST node? Cause then it would be easy.

**Comment by paulflang** [comment]
I just realised that I cannot match for `time`. Cause someone could do this:
```
<math xmlns="http://www.w3.org/1998/Math/MathML"> 
    <apply> 
        <plus/> 
        <ci> x </ci> 
        <csymbol encoding="text" definitionURL="http://www.sbml.org/sbml/symbols/time"> 
            zeit_is_german_for_time
        </csymbol> 
    </apply> 
</math>
```
In which case I would have to match for `zeit_is_german_for_time`. See also the definitionURL: http://sbml.org/Documents/Specifications/XML_Schemas/symbols/time

**Comment by exaexa** [comment]
Oh my god, does that that you can have multiple time definitions? :D
```
<math xmlns="http://www.w3.org/1998/Math/MathML"> 
    <apply> 
        <plus/> 
        <ci> x </ci> 
        <csymbol encoding="text" definitionURL="http://www.sbml.org/sbml/symbols/time"> 
            zeit_is_german_for_time
        </csymbol> 
        <csymbol encoding="text" definitionURL="http://www.sbml.org/sbml/symbols/time"> 
            different_timezone_sorry
        </csymbol> 
        <csymbol encoding="text" definitionURL="http://www.sbml.org/sbml/symbols/time"> 
            час_реакцие
        </csymbol> 
    </apply> 
</math>
```
Would the different variables mean something or is it all just one single "time" ?

**Comment by paulflang** [comment]
You might be right. And if you are, the correct translation of this into MTK would be:
`x + Catalyst.Default_IV + Catalyst.Default_IV + Catalyst.Default_IV`

**Comment by exaexa** [comment]
So the choices are:
- there's just one time, we get SBML.MathTime that you translate to your time variable
- there are multiple times that need to be differentiated by the name (e.g. `time`), which you translate to your time variable
- there needs to be distinction between time and variables because it may collide with a variable named `time`

For our own safety I'm choosing the possibility number 3 now. I'd love to hear whether SBML standard explicitly disallows any of this.

**Comment by paulflang** [comment]
Well, the distinction of your third point is there in SBML: every csymbol with definitionURL="http://www.sbml.org/sbml/symbols/time" semantically means time, regardless of its string attribute (name it `time`, `t`, `zeit`, whatever you want, it always means time). We just need to figure out how it can be parsed into `SBML.MathTime`. If we cannot figure out if the AST node is of type `AST_NAME_TIME`, can we at least access the definitionURL via libsbml as workaround solution?

**Comment by paulflang** [comment]
I think the function we should use is [ASTNode_getType](http://model.caltech.edu/software/libsbml/5.18.0/docs/formatted/c-api/class_a_s_t_node__t.html#aad6cd351567a177ab88b961890f18c7c).

**Comment by exaexa** [comment]
Yap I'm already using it. Unfortunately the constants aren't really named. But that isn't the first unnamed constant we have. :rofl: 


(actually :sob:)
