### ISSUE TITLE
Find and add good tests for loading converters

### ISSUE THREAD

**Issue by exaexa** [LCSB-BioCore/SBML.jl#56]
> is there some good way/data to test this?

I created these test for the converters: https://github.com/paulflang/SBML.jl/blob/pl/mk-species-units/test/loaddynamicmodels.jl

_Originally posted by @paulflang in https://github.com/LCSB-BioCore/SBML.jl/issues/55#issuecomment-855837778_

**Comment by paulflang** [comment]
I am on it.
