### ISSUE TITLE
Make `GPAAnd` and `GPAOr` parametric?

### ISSUE THREAD

**Issue by giordano** [LCSB-BioCore/SBML.jl#72]
Currently, `GPAAnd` and `GPAOr` are defined as
https://github.com/LCSB-BioCore/SBML.jl/blob/d4a382e734db7b18f0694f4985dc9a6d6864e46e/src/structs.jl#L47-L49
and
https://github.com/LCSB-BioCore/SBML.jl/blob/d4a382e734db7b18f0694f4985dc9a6d6864e46e/src/structs.jl#L54-L56
but `GeneProductAssociation` is an abstract type, which violates [one of the perfomance tips](https://docs.julialang.org/en/v1/manual/performance-tips/#man-performance-abstract-container).  Would it make sense to make these types parametric?
```julia
struct GPAAnd{GPA<:GeneProductAssociation} <: GeneProductAssociation
    terms::Vector{GPA}
end
struct GPAOr{GPA<:GeneProductAssociation} <: GeneProductAssociation
    terms::Vector{GPA}
end
```

Related, `MathLambda` has a field, `body`, with an abstract type, `Math`:
https://github.com/LCSB-BioCore/SBML.jl/blob/d4a382e734db7b18f0694f4985dc9a6d6864e46e/src/structs.jl#L104-L107

**Comment by exaexa** [comment]
Hi!
One problem may be that e.g. the "And" expression may contain both other "Or" expressions and single atom terms (aka MathIdent). Would that work?
Anyway speed isn't really a priority here, the expressions are usually smaller than 30 terms and (HOPEFULLY) no one will ever interpret this stuff directly. :D

**Comment by exaexa** [comment]
side notes:
- if this is the cause of relatively low processing speed of math, let's just change it to the fast :]
- the type should be a reminiscent of the usual AST, so a bit of pointers in the vectors is kinda expected

**Comment by giordano** [comment]
> One problem may be that e.g. the "And" expression may contain both other "Or" expressions and single atom terms (aka MathIdent). Would that work?

Yes, because a vector of "And" and "Or"
```julia
julia> [SBML.GPAAnd([SBML.GPARef("foo")]), SBML.GPAOr([SBML.GPARef("bar")])]
2-element Vector{SBML.GeneProductAssociation}:
 SBML.GPAAnd(SBML.GeneProductAssociation[SBML.GPARef("foo")])
 SBML.GPAOr(SBML.GeneProductAssociation[SBML.GPARef("bar")])
```
is a `Vector{SBML.GeneProductAssociation}`, so it'd still match the proposed signature, it will just not be any better then the current situation.

Given the fact performance isn't a concern at the moment and that you need to have heterogeneous vectors, being more specific is not going to help much.  Thanks for the discussion!
