### ISSUE TITLE
Stable docs don't seem to be updated

### ISSUE THREAD

**Issue by exaexa** [LCSB-BioCore/SBML.jl#92]
This is most likely for @laurentheirendt -- I just noticed that the docs here https://lcsb-biocore.github.io/SBML.jl/stable/ point to a really historic version; same thing at `dev/` looks updated though.Stable link seems pointing to 0.4.0 now...

I kinda hope I didn't break anything back then. :D

**Comment by laurentheirendt** [comment]
I think this can be closed now ...
